/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownloadModal: typeof import('./src/components/DownloadModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarTrails: typeof import('./src/components/StarTrails.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
